[package]
name = "roxido_faer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxido = { path = "../roxido" }
faer-core = "0.9"
