export NOT_CRAN := "true"

all: rust_fn package

rust_fn:
    cd ../cargo/tests; R CMD BATCH testthat.R
    mv ../cargo/tests/testthat.Rout rust_fn.Rout

package:
    rm -rf testpkg
    Rscript -e "cargo::new_package('testpkg')"
    R CMD INSTALL testpkg
    Rscript -e "cargo::prebuild('testpkg')"
    R CMD build testpkg
    R CMD check --as-cran --no-manual testpkg_0.1.0.tar.gz
    Rscript -e "set.seed(234); testpkg::myrnorm(3,0,1)"
