#!/usr/bin/fish

for pkg in (./list-all-packages)
    echo "-----------------------------------------------------------------------------------------"
    cd $pkg/src/rust
    cargo update
    cd roxido
    cargo update
    cd ../roxido_macro
    cargo update
    cargo upgrades
end
