#!/usr/bin/fish

for pkg in (./list-all-packages)
    echo "-----------------------------------------------------------------------------------------"
    echo $pkg
	cd $pkg
	cd src/rust
	cargo msrv
end
