#!/usr/bin/fish

while not test -f DESCRIPTION
  if test (pwd) = /
    echo "ERROR: Could not find DESCRIPTION file." >&2
    exit 1
  end
  cd ..
end

if string length -q -- (git status --untracked-files=no --porcelain)
  echo "WARNING: Git repository is not clean." >&2
end

set base ~/docs/devel/roxidoExample

for x in src/rust/roxido/src/print.rs src/rust/roxido/src/stop.rs src/rust/roxido/src/r.rs
  if test -e $PWD/$x
    git rm $PWD/$x
  end
end

for x in src/rust/roxido/src/lib.rs \
  set fullsrc $base/$x
  if test -e $PWD/$x
    cp $fullsrc $PWD/$x
  end
end
