scp_dest := "dahl:public"  # Change this to match the 'configure' script.

build:
  rm -f *.tar.gz
  R CMD build .
  R CMD INSTALL *.tar.gz

prebuild:
  Rscript -e 'cargo::prebuild(what="all")'
  scp -r src/rust/r_cargo_cross_compile {{scp_dest}}
  
