cran: && build
  Rscript -e 'cargo::prebuild(what="all")'

nocran: && build
  cd src/rust; rm -rf .cargo vendor.tar.xz

install: build
  R CMD INSTALL *.tar.gz

build:
  rm -f *.tar.gz
  R CMD build .

reinstall:
  R CMD INSTALL .

