clean:
  cd src/rust; Rscript -e 'cargo::run("clean")'

cran: && build
  Rscript -e 'cargo::prebuild(what="all")'

nocran: && build
  cd src/rust; rm -rf .cargo vendor.tar.xz

build:
  R CMD build .

install target=default_target:
  R CMD INSTALL {{target}}

default_target := "."
